### PR TITLE
Fix generation of the CREATOR field for Kotlin Android Parcelables

### LINKED ISSUE #705: Incorrect Android Parcelable implementation generated
The IDE complains about the `CREATOR` field missing. Currently it's being generated as:
```kotlin
class Foo {
  ...
  object CREATOR : Parcelable.Creator<Foo> {
    ...
  }
}
```
while it should be the following in order for Android to find it:
```kotlin
class Foo {
  ...
  companion object {
    @JvmStatic val CREATOR = object : Parcelable.Creator<Foo> {
      ...
    }
  }
}
```

### PR DESCRIPTION
**Pull request by Egorand**
Fixes #705

### CODE REVIEW

File: wire-tests/src/test/java/com/squareup/wire/java/KotlinGeneratorTest.kt [hunk 1]
```diff
@@ -88,7 +88,10 @@ class KotlinGeneratorTest {
         .addImport("com.squareup.wire.kotlin", "decodeMessage")
         .build()
     val code = fileSpec.toString()
-    assertTrue(code.contains("object CREATOR : Parcelable.Creator<PhoneNumber>"))
+    assertTrue(code.contains("companion object"))
+    assertTrue(code.contains("@JvmStatic"))
+    assertTrue(code.contains("val CREATOR"))
+    assertTrue(code.contains("object : Parcelable.Creator<PhoneNumber>"))
```
Comment (JakeWharton) [inline wire-tests/src/test/java/com/squareup/wire/java/KotlinGeneratorTest.kt]: I'm skeptical of this testing strategy since the integration test already covers all of this implicitly

Comment (Egorand) [reply wire-tests/src/test/java/com/squareup/wire/java/KotlinGeneratorTest.kt]: Agree, and `assertTrue` is particularly unhelpful. However, I don't think integration testing is configured properly, since my changes didn't break any tests except for this one.

**Comment by Egorand** [comment]
Planning to rebase on #712 when it's merged
