### PR TITLE
Wrap oneof error message properly

### LINKED ISSUE #991: Error message wrapped incorrectly in a oneof class in Java interop mode
image

The error message used in `oneOf`s is wrapped without making the whole thing one string.

### PR DESCRIPTION
**Pull request by Egorand**
Fixes #991

### CODE REVIEW

File: wire-tests/src/test/proto-kotlin/com/squareup/wire/protos/kotlin/Form.kt [hunk 1]
```diff
@@ -0,0 +1,765 @@
...
+    adapter = "com.squareup.wire.protos.kotlin.Form${'$'}CurrencyConversionFlagsElement#ADAPTER"
+  )
+  val currency_conversion_flags_element: CurrencyConversionFlagsElement? = null,
+  val unknownFields: ByteString = ByteString.EMPTY
+) : Message<Form, Form.Builder>(ADAPTER, unknownFields) {
+  init {
+    require(countNonNull(button_element, local_image_element, remote_image_element, money_element,
+        spacer_element, text_element, customized_card_element, address_element, text_input_element,
+        option_picker_element, detail_row_element, currency_conversion_flags_element) <= 1) {
+      "At most one of button_element, local_image_element, remote_image_element, money_element, spacer_element, text_element, customized_card_element, address_element, text_input_element, option_picker_element, detail_row_element, currency_conversion_flags_element may be non-null"
```
Comment (oldergod) [inline wire-tests/src/test/proto-kotlin/com/squareup/wire/protos/kotlin/Form.kt]: hmmm, there's no wrapping though? Shouldn't we break lines?

Comment (Egorand) [reply wire-tests/src/test/proto-kotlin/com/squareup/wire/protos/kotlin/Form.kt]: Nope, strings don't wrap.
