### PR TITLE
object methods still work for our gRPC services

### LINKED ISSUE #1180: gRPC: handle `routeGuideService.toString()` without crashing

### PR DESCRIPTION
**Pull request by oldergod**
fixes #1180

### CODE REVIEW

File: wire-grpc-client/src/main/java/com/squareup/wire/GrpcClient.kt [hunk 1]
```diff
@@ -37,11 +38,24 @@ class GrpcClient private constructor(
...
+            if (method.declaringClass == Object::class.java) {
+              return if (args == null) {
+                method.invoke(self)
+              } else {
+                method.invoke(self, *args)
+              }
+            }
+
+            val grpcMethod = methodToService[method] as GrpcMethod<*, *>
+            return grpcMethod.invoke(this@GrpcClient, args ?: emptyArray())
```
Comment (JakeWharton) [inline wire-grpc-client/src/main/java/com/squareup/wire/GrpcClient.kt]: How about moving this `args ?: emptyArray` before the `if` to avoid doing it in both branches?

Comment (oldergod) [reply wire-grpc-client/src/main/java/com/squareup/wire/GrpcClient.kt]: why not, done
