### PR TITLE
Pruning rules: Most precise rule takes precedence, and we crash for conflicting rules.

### LINKED ISSUE #1349: Update pruning behaviour to give precedence to the most precise rule
part of #1243

Right now excluding rules take precedence however precise they are compared to including ones.
We wanna update that to let the most precise rule get priority when pruning. If exclusion and inclusion are equal, exclusion takes precedence.

### PR DESCRIPTION
**Pull request by oldergod**
related to #1243 
fixes #1349

### CODE REVIEW

File: wire-schema/src/jvmTest/kotlin/com/squareup/wire/schema/PruningRulesTest.kt [hunk 1]
```diff
@@ -223,18 +237,15 @@ class PruningRulesTest {
...
         .build()
     set.includes(ProtoMember.get("a.IncludedType#member"))
-    assertThat(set.unusedExcludes()).containsExactly("a.IncludedType")
+    assertThat(set.unusedExcludes()).containsExactly("a.*")
   }
 
-  @Test
-  fun trackingUnusedPrecedence() {
-    val set = PruningRules.Builder()
+  @Test(expected = IllegalStateException::class)
```
[the remark this answers is not in the document]
Comment (oldergod) [reply wire-schema/src/jvmTest/kotlin/com/squareup/wire/schema/PruningRulesTest.kt]: addressed

File: wire-schema/src/jvmMain/java/com/squareup/wire/schema/PruningRules.kt [hunk 2]
```diff
@@ -226,6 +230,10 @@ class PruningRules private constructor(builder: Builder) {
       check(oldest == null || newest == null || oldest!! <= newest!!) {
         "expected oldest $oldest <= newest $newest"
       }
+      val conflictingRules = includes.intersect(excludes)
+      check(conflictingRules.isEmpty()) {
+        "same rule(s) defined in both includes and excludes: ${conflictingRules.joinToString()}"
```
Comment (Egorand) [inline wire-schema/src/jvmMain/java/com/squareup/wire/schema/PruningRules.kt]: supernit: `Same`

File: wire-schema/src/jvmMain/java/com/squareup/wire/schema/PruningRules.kt [hunk 3]
```diff
@@ -125,28 +126,27 @@ class PruningRules private constructor(builder: Builder) {
...
-      }
-      includeMatch != null -> {
-        usedIncludes.add(includeMatch)
-        true
-      }
-      else -> {
-        false
-      }
+    val isRoot = when {
+      excludeMatch != null && includeMatch != null -> excludeMatch.length < includeMatch.length
```
Comment (swankjesse) [inline wire-schema/src/jvmMain/java/com/squareup/wire/schema/PruningRules.kt]: I think it matters if one is a type and the other is not. This is relevant when pruning the field type vs. the enclosing type. In other words, `a.b.C#d` is effectively longer than `a.b.e.Elephant` even though the string is shorter.

File: wire-schema/src/jvmMain/java/com/squareup/wire/schema/PruningRules.kt [hunk 4]
```diff
@@ -125,28 +126,27 @@ class PruningRules private constructor(builder: Builder) {
...
+      excludeMatch != null -> false
+      includeMatch != null -> true
+      else -> false
     }
+    if (isRoot) {
+      usedIncludes.add(includeMatch!!)
+    } else {
```
Comment (swankjesse) [inline wire-schema/src/jvmMain/java/com/squareup/wire/schema/PruningRules.kt]: should this be `else if` ?

File: wire-schema/src/jvmMain/java/com/squareup/wire/schema/PruningRules.kt [hunk 5]
```diff
@@ -160,24 +160,28 @@ class PruningRules private constructor(builder: Builder) {
...
-    return when {
-      excludeMatch != null -> {
-        usedExcludes.add(excludeMatch)
-        true
-      }
-      else -> {
-        false
-      }
+    val excluded = when {
+      excludeMatch != null && includeMatch != null -> excludeMatch.length >= includeMatch.length
```
Comment (swankjesse) [inline wire-schema/src/jvmMain/java/com/squareup/wire/schema/PruningRules.kt]: similar to above, strict string length is too simple

File: wire-schema/src/jvmTest/kotlin/com/squareup/wire/schema/PruningRulesTest.kt [hunk 6]
```diff
@@ -223,18 +238,20 @@ class PruningRulesTest {
...
   @Test
-  fun trackingUnusedPrecedence() {
-    val set = PruningRules.Builder()
-        .include("a.*")
-        .exclude("a.*")
-        .build()
-    set.includes(ProtoType.get("a.Message"))
-    assertThat(set.unusedExcludes()).isEmpty()
-    assertThat(set.unusedIncludes()).containsExactly("a.*")
+  fun crashForConflictingRules() {
```
Comment (swankjesse) [inline wire-schema/src/jvmTest/kotlin/com/squareup/wire/schema/PruningRulesTest.kt]: nice test

File: wire-schema/src/jvmTest/kotlin/com/squareup/wire/schema/PruningRulesTest.kt [hunk 7]
```diff
@@ -223,18 +238,20 @@ class PruningRulesTest {
         .exclude("a.IncludedType")
         .build()
     set.includes(ProtoMember.get("a.IncludedType#member"))
-    assertThat(set.unusedExcludes()).containsExactly("a.IncludedType")
+    assertThat(set.unusedExcludes()).containsExactly("a.*")
   }
 
   @Test
-  fun trackingUnusedPrecedence() {
```
Comment (swankjesse) [inline wire-schema/src/jvmTest/kotlin/com/squareup/wire/schema/PruningRulesTest.kt]: what happened to this?

File: wire-schema/src/jvmMain/java/com/squareup/wire/schema/PruningRules.kt (hunk 3 above)
Comment (oldergod) [reply wire-schema/src/jvmMain/java/com/squareup/wire/schema/PruningRules.kt]: When would that happen though? the longest identifier will always contain the short one if we have both an `excludeMatch` and an `includeMatch`, they cannot both match without one containing the other.

File: wire-schema/src/jvmMain/java/com/squareup/wire/schema/PruningRules.kt (hunk 2 above)
Comment (oldergod) [reply wire-schema/src/jvmMain/java/com/squareup/wire/schema/PruningRules.kt]: We don't capitalize the error message just above so I just did the _same_.

File: wire-schema/src/jvmTest/kotlin/com/squareup/wire/schema/PruningRulesTest.kt (hunk 7 above)
Comment (oldergod) [reply wire-schema/src/jvmTest/kotlin/com/squareup/wire/schema/PruningRulesTest.kt]: We cannot have conflicting rules anymore (this crashes). We already have tests when include/exclude are of different precision so I killed it.

File: wire-schema/src/jvmMain/java/com/squareup/wire/schema/PruningRules.kt (hunk 3 above)
Comment (oldergod) [reply wire-schema/src/jvmMain/java/com/squareup/wire/schema/PruningRules.kt]: When would that happen though? the longest identifier will always contain the short one if we have both an excludeMatch and an includeMatch, they cannot both match without one containing the other.

File: wire-schema/src/jvmMain/java/com/squareup/wire/schema/PruningRules.kt (hunk 4 above)
Comment (oldergod) [reply wire-schema/src/jvmMain/java/com/squareup/wire/schema/PruningRules.kt]: Fixed!

File: wire-schema/src/jvmMain/java/com/squareup/wire/schema/MarkSet.kt [hunk 8]
```diff
@@ -52,6 +59,28 @@ class MarkSet(
     types.add(type)
   }
 
+  /**
+   * Marks a type as transitively reachable by the includes set. Returns true if the mark is new,
+   * the type will be retained, and reachable objects should be traversed.
+   * Even though `type` might be excluded, it will be retained if it is one the root member's
+   * actual type.
+   */
+  fun mark(type: ProtoType, reference: ProtoMember): Boolean {
```
Comment (oldergod) [inline wire-schema/src/jvmMain/java/com/squareup/wire/schema/MarkSet.kt]: TODO(benoit) add test if people approves this approach.

File: wire-schema/src/jvmMain/java/com/squareup/wire/schema/MarkSet.kt [hunk 9]
```diff
@@ -31,9 +31,15 @@ class MarkSet(
...
   val types = mutableSetOf<ProtoType>()
+  /** The types excluded by the pruning rules. */
+  private val excludedTypes = mutableSetOf<ProtoType>()
 
   /** The members to retain. Any member not in here should be pruned! */
   val members = mutableMapOf<ProtoType, MutableSet<ProtoMember>>()
+  /** The root members which are never to be pruned, including their actual type. */
+  private val rootMemberTypes = mutableMapOf<ProtoMember, ProtoType?>()
+  /** The members this MarkSet have seen. The values should be non-null once the marking is done. */
+  private val memberTypes = mutableMapOf<ProtoMember, ProtoType?>()
```
Comment (oldergod) [inline wire-schema/src/jvmMain/java/com/squareup/wire/schema/MarkSet.kt]: Maybe create a class to handle that

File: wire-schema/src/jvmMain/java/com/squareup/wire/schema/MarkSet.kt [hunk 10]
```diff
@@ -34,6 +34,10 @@ class MarkSet(
 
   /** The members to retain. Any member not in here should be pruned! */
   val members = mutableMapOf<ProtoType, MutableSet<ProtoMember>>()
+  /** The root members which are never to be pruned, including their actual type. */
```
Comment (swankjesse) [inline wire-schema/src/jvmMain/java/com/squareup/wire/schema/MarkSet.kt]: “actual type“ means referenced type? I want a better word but I can’t think of one

File: wire-schema/src/jvmMain/java/com/squareup/wire/schema/MarkSet.kt [hunk 11]
```diff
@@ -42,6 +46,7 @@ class MarkSet(
   fun root(protoMember: ProtoMember) {
     check(!pruningRules.excludes(protoMember))
     types.add(protoMember.type)
+    rootMemberTypes[protoMember] = null
```
Comment (swankjesse) [inline wire-schema/src/jvmMain/java/com/squareup/wire/schema/MarkSet.kt]: Worthwhile using a value other than null as a placeholder?

val UNKNOWN_TYPE = ProtoType.get("(unknown type)")

File: wire-schema/src/jvmMain/java/com/squareup/wire/schema/MarkSet.kt (hunk 10 above)
Comment (swankjesse) [reply wire-schema/src/jvmMain/java/com/squareup/wire/schema/MarkSet.kt]: I prefer _referenced type_ here, which is what you use on line 66 anyway

File: wire-schema/src/jvmMain/java/com/squareup/wire/schema/MarkSet.kt [hunk 12]
```diff
@@ -52,6 +57,24 @@ class MarkSet(
     types.add(type)
   }
 
+  /**
+   * Marks a type as transitively reachable by the includes set. Returns true if the mark is new,
+   * the type will be retained, and reachable objects should be traversed.
+   * Even though `type` might be excluded, it will be retained if it is one the root member's
```
Comment (swankjesse) [inline wire-schema/src/jvmMain/java/com/squareup/wire/schema/MarkSet.kt]: Can I rephrase this sentence?

```
If there is an exclude for [type], non-root members referencing it will be pruned. The type itself will also be pruned unless is referenced by a root member.
```

Comment (oldergod) [reply wire-schema/src/jvmMain/java/com/squareup/wire/schema/MarkSet.kt]: fixed

File: wire-schema/src/jvmMain/java/com/squareup/wire/schema/MarkSet.kt (hunk 11 above)
Comment (oldergod) [reply wire-schema/src/jvmMain/java/com/squareup/wire/schema/MarkSet.kt]: fixed

File: wire-schema/src/jvmMain/java/com/squareup/wire/schema/MarkSet.kt (hunk 10 above)
Comment (oldergod) [reply wire-schema/src/jvmMain/java/com/squareup/wire/schema/MarkSet.kt]: fixed
