### PR TITLE
Handle negative hexadecimal as default values

### LINKED ISSUE #3348: NumberFormatException when using negative hexadecimal numbers
I tried switching from google's protobufs to this project for the better kotlin support, but I am running into to issue that appears to be caused by:

```
optional int32 someVariable = 3 [default = -0x80000000];
```

```
Caused by: java.lang.NumberFormatException: For input string: "x80000000"
```

It looks like https://github.com/square/wire/pull/661 fixed this for positive hexadecimal numbers but not negative ones.

### PR DESCRIPTION
**Pull request by oldergod**
Fixes #3348

### CODE REVIEW

File: wire-schema/src/jvmMain/kotlin/com/squareup/wire/schema/internal/JvmLanguages.kt [hunk 1]
```diff
@@ -119,10 +119,17 @@ fun optionValueToInt(value: Any?): Int {
...
 
   return when {
     // Hexadecimal.
-    string.startsWith("0x") || string.startsWith("0X") -> string.substring("0x".length).toInt(16)
+    string.startsWith("${negativeSign}0x", ignoreCase = true) ->
+      buildString {
+        append(string.substring("${negativeSign}0x".length))
+        if (negativeSign.isNotBlank()) {
+          insert(0, '-')
+        }
```
Comment (squarejesse) [inline wire-schema/src/jvmMain/kotlin/com/squareup/wire/schema/internal/JvmLanguages.kt:131]:
```suggestion
        append(negativeSign)
        append(string.substring("${negativeSign}0x".length))
```

File: wire-schema/src/jvmMain/kotlin/com/squareup/wire/schema/internal/JvmLanguages.kt [hunk 2]
```diff
@@ -136,10 +143,17 @@ fun optionValueToLong(value: Any?): Long {
...
 
   return when {
     // Hexadecimal.
-    string.startsWith("0x") || string.startsWith("0X") -> string.substring("0x".length).toLong(16)
+    string.startsWith("${negativeSign}0x", ignoreCase = true) ->
+      buildString {
+        append(string.substring("${negativeSign}0x".length))
+        if (negativeSign.isNotBlank()) {
+          insert(0, '-')
+        }
```
Comment (squarejesse) [inline wire-schema/src/jvmMain/kotlin/com/squareup/wire/schema/internal/JvmLanguages.kt:155]:
```suggestion
        append(negativeSign)
        append(string.substring("${negativeSign}0x".length))
```

**Review by squarejesse — APPROVED** [review]
